server:
  port: 8088
spring:
  application:
    name: springbootoauth2demo
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-oauth2-demo
            client-secret: secret-key
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/test-realm1
            user-name-attribute: preferred_username